# Generated by Django 3.1.6 on 2021-02-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poketrader', '0002_auto_20210215_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokeapi_id',
        ),
    ]
