# Generated by Django 3.1.6 on 2021-02-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poketrader', '0003_remove_pokemon_pokeapi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonComparison',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('list1', models.ManyToManyField(
                    related_name='list1', to='poketrader.Pokemon')),
                ('list2', models.ManyToManyField(
                    related_name='list2', to='poketrader.Pokemon')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
